services:
  db:
    image: adinaildoribeiro/fiap-soat11-db:v4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fiap-soat11@pass
      MYSQL_DATABASE: fiap
      MYSQL_USER: user_fiap
      MYSQL_PASSWORD: pass_fiap
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network
  
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: fiaprabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge